# Generated by Django 3.0.5 on 2020-05-03 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Squirrel',
            fields=[
                ('unique_squirrel_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('date', models.DateTimeField(null=True, verbose_name='Date')),
            ],
        ),
    ]
