# Generated by Django 3.0.5 on 2020-05-12 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Squirrel',
            fields=[
                ('unique_squirrel_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('latitude', models.FloatField(max_length=20, null=True, verbose_name='latitude')),
                ('longitude', models.FloatField(max_length=20, null=True, verbose_name='longitude')),
                ('shift', models.CharField(choices=[('AM', 'AM'), ('PM', 'PM')], default='AM', max_length=2, verbose_name='shift')),
                ('date', models.DateTimeField(null=True, verbose_name='Date')),
                ('age', models.CharField(max_length=10, null=True, verbose_name='Age')),
                ('primary_fur_color', models.CharField(max_length=100, null=True, verbose_name='Primary Fur Color')),
                ('specific_location', models.CharField(max_length=100, null=True, verbose_name='Specific Location')),
                ('running', models.CharField(choices=[('true', 'True'), ('false', 'False'), ('', '')], default='', max_length=10, verbose_name='running')),
                ('chasing', models.CharField(choices=[('true', 'True'), ('false', 'False'), ('', '')], default='', max_length=10, verbose_name='chasing')),
                ('climbing', models.CharField(choices=[('true', 'True'), ('false', 'False'), ('', '')], default='', max_length=10, verbose_name='climbing')),
                ('eating', models.CharField(choices=[('true', 'True'), ('false', 'False'), ('', '')], default='', max_length=10, verbose_name='eating')),
                ('foraging', models.CharField(choices=[('true', 'True'), ('false', 'False'), ('', '')], default='', max_length=10, verbose_name='foraging')),
                ('other_activities', models.CharField(max_length=100, null=True, verbose_name='other activities')),
                ('kuks', models.CharField(choices=[('true', 'True'), ('false', 'False'), ('', '')], default='', max_length=10, verbose_name='kuks')),
                ('quaas', models.CharField(choices=[('true', 'True'), ('false', 'False'), ('', '')], default='', max_length=10, verbose_name='quaas')),
                ('moans', models.CharField(choices=[('true', 'True'), ('false', 'False'), ('', '')], default='', max_length=10, verbose_name='moans')),
                ('tail_flags', models.CharField(choices=[('true', 'True'), ('false', 'False'), ('', '')], default='', max_length=10, verbose_name='tail flags')),
                ('tail_twitches', models.CharField(choices=[('true', 'True'), ('false', 'False'), ('', '')], default='', max_length=10, verbose_name='tail twitches')),
                ('approaches', models.CharField(choices=[('true', 'True'), ('false', 'False'), ('', '')], default='', max_length=10, verbose_name='approaches')),
                ('indifferent', models.CharField(choices=[('true', 'True'), ('false', 'False'), ('', '')], default='', max_length=10, verbose_name='indifferent')),
                ('runs_from', models.CharField(choices=[('true', 'True'), ('false', 'False'), ('', '')], default='', max_length=10, verbose_name='runs_from')),
            ],
        ),
    ]
