# Generated by Django 3.0.5 on 2020-05-12 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='squirrel',
            name='age',
            field=models.CharField(max_length=10, null=True, verbose_name='Age'),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='approaches',
            field=models.CharField(choices=[('true', 'True'), ('false', 'False'), ('', '')], default='', max_length=10, verbose_name='approaches'),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='chasing',
            field=models.CharField(choices=[('true', 'True'), ('false', 'False'), ('', '')], default='', max_length=10, verbose_name='chasing'),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='climbing',
            field=models.CharField(choices=[('true', 'True'), ('false', 'False'), ('', '')], default='', max_length=10, verbose_name='climbing'),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='eating',
            field=models.CharField(choices=[('true', 'True'), ('false', 'False'), ('', '')], default='', max_length=10, verbose_name='eating'),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='foraging',
            field=models.CharField(choices=[('true', 'True'), ('false', 'False'), ('', '')], default='', max_length=10, verbose_name='foraging'),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='indifferent',
            field=models.CharField(choices=[('true', 'True'), ('false', 'False'), ('', '')], default='', max_length=10, verbose_name='indifferent'),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='kuks',
            field=models.CharField(choices=[('true', 'True'), ('false', 'False'), ('', '')], default='', max_length=10, verbose_name='kuks'),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='latitude',
            field=models.FloatField(max_length=20, null=True, verbose_name='latitude'),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='longitude',
            field=models.FloatField(max_length=20, null=True, verbose_name='longitude'),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='moans',
            field=models.CharField(choices=[('true', 'True'), ('false', 'False'), ('', '')], default='', max_length=10, verbose_name='moans'),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='other_activities',
            field=models.CharField(max_length=100, null=True, verbose_name='other activities'),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='primary_fur_color',
            field=models.CharField(max_length=100, null=True, verbose_name='Primary Fur Color'),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='quaas',
            field=models.CharField(choices=[('true', 'True'), ('false', 'False'), ('', '')], default='', max_length=10, verbose_name='quaas'),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='running',
            field=models.CharField(choices=[('true', 'True'), ('false', 'False'), ('', '')], default='', max_length=10, verbose_name='running'),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='runs_from',
            field=models.CharField(choices=[('true', 'True'), ('false', 'False'), ('', '')], default='', max_length=10, verbose_name='runs_from'),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='shift',
            field=models.CharField(choices=[('AM', 'AM'), ('PM', 'PM')], default='AM', max_length=2, verbose_name='shift'),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='specific_location',
            field=models.CharField(max_length=100, null=True, verbose_name='Specific Location'),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='tail_flags',
            field=models.CharField(choices=[('true', 'True'), ('false', 'False'), ('', '')], default='', max_length=10, verbose_name='tail flags'),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='tail_twitches',
            field=models.CharField(choices=[('true', 'True'), ('false', 'False'), ('', '')], default='', max_length=10, verbose_name='tail twitches'),
        ),
    ]
