# Generated by Django 3.0.5 on 2020-05-12 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrel',
            name='unique_squirrel_id',
            field=models.CharField(help_text='Unique Squirrel ID', max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
