# Generated by Django 3.0.5 on 2020-05-12 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0002_auto_20200512_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrel',
            name='unique_squirrel_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='Unique Squirrel ID'),
        ),
    ]
